version: '3'

services:
  nodejs:
    image: "nigulh/sixfold"
    build:
      context: '.'
      dockerfile: "./Dockerfile"
    ports:
      - "3033:8080"
    volumes:
      - ./src:/usr/app/src:delegated
      - ./__tests__:/usr/app/__tests__:delegated

  swagger:
    image: "swaggerapi/swagger-ui"
    ports:
      - "3080:8080"
    volumes:
      - ./api:/api
    environment:
      SWAGGER_JSON: /api/swagger.json


# export BUILDKIT_PROGRESS=plain; docker-compose up
# docker-compose rm --all && docker-compose pull && docker-compose build --no-cache && docker-compose up -d --force-recreate
